
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.


#include "Arduino.h"

#include "config.h"
#include "mpack/mpack.h"
#include "mpack/mpack-platform.h"

void TUT3__config_clean(struct TUT3__config *self) {

	self->lower_bound = 0;
	self->upper_bound = 0;
}

void TUT3__config_parse_next(struct TUT3__config *self, mpack_reader_t *reader) {

	char	buf_key[12];
	mpack_expect_utf8_cstr(reader, buf_key, sizeof(buf_key));


	if (mpack_memcmp("lower_bound",(const char*)buf_key,11) == 0) {
		self->lower_bound = mpack_expect_i32(reader);
	}

	if (mpack_memcmp("upper_bound",(const char*)buf_key,11) == 0) {
		self->upper_bound = mpack_expect_i32(reader);
	}


}

int TUT3__config_parse(struct TUT3__config *self, const uint8_t *input_buf, size_t sz_input_buf) {
		mpack_reader_t reader;
    mpack_error_t error;

    mpack_reader_init_data(&reader,(const char *)input_buf, sz_input_buf);
    self->TUT3__config_parse_mpack(self, &reader);

    error = mpack_reader_destroy(&reader);
    if ( error != mpack_ok) {
        return 1;
    } else {
        return 0;
    }

}

void TUT3__config_parse_mpack(struct TUT3__config *self, mpack_reader_t *reader) {

    int count = mpack_expect_map_range(reader, 0, 2);
    for (int i = 0; i < count; i++) {
        TUT3__config_parse_next(self, reader);
    }

    mpack_done_map(reader);
}

size_t TUT3__config_serialize(const struct TUT3__config *self, uint8_t *output_buf, size_t sz_output_buf) {
		struct mpack_writer_t writer;
    mpack_writer_init(&writer,(char*)output_buf,sz_output_buf);

		self->TUT3__config_serialize_mpack(self, &writer);

    // if all is ok, return length of used bytes. Otherwise 0
    if (mpack_writer_destroy(&writer) == mpack_ok) {
        return writer.used;
    } else {
        return (size_t)0;
    }
}

void TUT3__config_serialize_mpack(const struct TUT3__config *self, mpack_writer_t *writer) {
    mpack_start_map(writer, 2);

	mpack_write_cstr(writer, "lower_bound"); mpack_write_i32(writer, self->lower_bound);
	mpack_write_cstr(writer, "upper_bound"); mpack_write_i32(writer, self->upper_bound);

    mpack_finish_map(writer);
}

void TUT3__config_init(struct TUT3__config *self) {
    self->TUT3__config_clean = &TUT3__config_clean;
    self->TUT3__config_parse = &TUT3__config_parse;
    self->TUT3__config_parse_mpack = &TUT3__config_parse_mpack;
    self->TUT3__config_serialize = &TUT3__config_serialize;
    self->TUT3__config_serialize_mpack = &TUT3__config_serialize_mpack;
    self->TUT3__config_clean(self);
}

//
