

// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// slyftlet=c99-generic-msgpack

#ifndef tut3_STATE_H
#define tut3_STATE_H

#include "mpack/mpack.h"

struct TUT3__state {
  bool	switch_on;
  char	led1[4];

  /**
  * Wipes contents to \0
  * @param self      pointer to target struct TUT3__state
  */
  void (*TUT3__state_clean)(struct TUT3__state *self);

  /**
  * Given an input buffer and its size, this functions parses the elements
  * of struct TUT3__state
  * @param self          pointer to target struct TUT3__state
  * @param input_buf     input buffer
  * @param sz_input_buf  size of input buffer
  * @return 0=success, 1=error
  */
  int (*TUT3__state_parse)(struct TUT3__state *self, const uint8_t *input_buf, size_t sz_input_buf);

  /**
  * Given a msgpack reader, this functions parses the elements
  * of struct TUT3__state
  * @param self          pointer to target struct TUT3__state
  * @param reader        pointer to mpack reader struct
  */
  void (*TUT3__state_parse_mpack)(struct TUT3__state *self, mpack_reader_t *reader);

  /**
  * Given a struct TUT3__state, this function serializes it into given output buffer.
  * @param self              pointer to source struct TUT3__state
  * @param output_buf        output buffer
  * @param sz_output_buf     size of output buffer
  * @return Length of output buf (0=error)
  */
  size_t (*TUT3__state_serialize)(const struct TUT3__state *self, uint8_t *output_buf, size_t sz_output_buf);

  /**
  * Given a struct TUT3__state, this function serializes it into given mpack writer.
  * @param self              pointer to source struct TUT3__state
  * @param writer 	         pointer to mpack writer struct
  */
  void (*TUT3__state_serialize_mpack)(const struct TUT3__state *self, mpack_writer_t *writer);

};

/**
 * Initializes struct struct TUT3__state. empties fields, sets function pointers
 * @param self  struct TUT3__state
 */
void TUT3__state_init(struct TUT3__state *self);


/* ORIGINAL SCHEMA
{"$schema"=>"http://json-schema.org/draft-04/schema#", "id"=>"state", "title"=>"Device state", "description"=>"", "type"=>"object", "properties"=>{"switch_on"=>{"type"=>"boolean"}, "led1"=>{"type"=>"string", "maxLength"=>3}}, "required"=>["switch_on", "led1", "led2"]}
 */
#endif		//tut3_STATE_H

